package com.example.tracker.util

import java.security.SecureRandom

// Mirrors web/js/utils.js#generateSessionId so links generated by either the web dashboard or
// this app share the same format and the same Firestore trust model: the id itself is the
// bearer credential for a tracking session (see /firestore.rules), so it must be long and
// generated with a CSPRNG, never sequential or short.
private const val ID_CHARS = "ABCDEFGHIJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789"
private val random = SecureRandom()

fun generateSessionId(length: Int = 22): String {
    val sb = StringBuilder(length)
    repeat(length) { sb.append(ID_CHARS[random.nextInt(ID_CHARS.length)]) }
    return sb.toString()
}
